Resequence events one more time in workflow

diff --git a/.github/workflows/daily-run.yml b/.github/workflows/daily-run.yml
--- a/.github/workflows/daily-run.yml
+++ b/.github/workflows/daily-run.yml
@@ -2,7 +2,9 @@ name: Daily Run
 
 on:
   schedule:
+    # Runs every day at 6am
     - cron: '0 6 * * *'
+  # Allows manual triggering
   workflow_dispatch:
 
 permissions:
@@ -14,6 +16,9 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  # Using a PAT with repo push access due to branch protection rules which are not supported with
+  # the automatic token provided by GitHub Actions at this time
+  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
   validate_pat:
     name: "Validate PAT"
     runs-on: ubuntu-latest
@@ -25,8 +30,8 @@ jobs:
             exit 1
           fi
 
-  fetch_articles:
-    name: "Fetch Articles"
+  build:
+    name: "Daily Run"
     runs-on: ubuntu-latest
     needs: validate_pat
     steps:
@@ -43,72 +48,17 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Fetch All Articles
+      - name: Generate Feed
         env:
           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-        run: npm run fetch:all-articles
+        run: ./tools/generate-feed.sh
 
-  generate_events_json:
-    name: "Generate Events JSON"
-    runs-on: ubuntu-latest
-    needs: fetch_articles
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GH_PAT }}
-
-      - name: Set up Node.js 18
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-
-      - name: Install dependencies
-        run: npm ci
-
-      - name: Generate Events JSON
-        env:
-          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-        run: npm run generate:events-json
-
-  generate_events_ics:
-    name: "Generate Events ICS"
-    runs-on: ubuntu-latest
-    needs: generate_events_json
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GH_PAT }}
-
-      - name: Set up Node.js 18
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-
-      - name: Install dependencies
-        run: npm ci
-
-      - name: Generate Events ICS
-        run: npm run generate:events-ics
-
-  publish_feed:
-    name: "Publish Feed"
-    runs-on: ubuntu-latest
-    needs: generate_events_ics
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GH_PAT }}
-
-      - name: Set up Node.js 18
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-
-      - name: Install dependencies
-        run: npm ci
+      - name: Validate Generation
+        run: |
+          if [ "$CONTINUE_NEXT" != "1" ]; then
+            echo "No feed updates required"
+            exit 1
+          fi
 
       - name: Configure Git
         run: |
